---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ apps_location }}"
    state: directory
    mode: '0755'

- name: Install unzip
  apt:
    name: unzip
    state: present
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)


- name: unzip jar
  ansible.builtin.unarchive:
    src: https://nexusrm.easlab.co.uk/repository/eas-hosted-bin/example-jar.tar.gz
    dest: "/usr/local/java-api/"
    remote_src: yes
    validate_certs: no


- name: make java-hello-app.service
  blockinfile:

    dest: /lib/systemd/system/java-hello-app.service
    block: |
      [Unit]
      Description=Java hello app

      [Service]
      Restart=on-failure
      ExecStart=java -jar {{ go_app_location }}/app.jar
      User=nobody
      Group=nogroup

      [Install]
      WantedBy=multi-user.target
    insertafter: EOF
    create: yes

- name: daemon-reload 
  command: systemctl daemon-reload

- name: enable myapp on start up
  command: systemctl enable java-hello-app