---
- hosts: all
  become: true
    

  vars:
    node_apps_location: /usr/local/java-api
    git_repo: https://github.com/Enterprise-Automation/java-gradle-hello-world.git

  vars_files:
    - vars/main.yml

  roles:
    - { role: appInstall ,  when: '"vm" in group_names'}
