---
- hosts: all
  become: true
    
  vars:
    node_apps_location: /usr/local/java-api

  vars_files:
    - vars/main.yml

  roles:
    - { role: java ,  when: '"vm" in group_names'}
    - { role: appInstall ,  when: '"vm" in group_names'}
