---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "/usr/java"
    state: directory
    mode: '0755'

- name: Download jre
  ansible.builtin.get_url:
    url: https://nexusrm.easlab.co.uk/repository/eas-hosted-bin/jdk-18_linux-x64_bin.rpm
    dest: /usr/java/jdk-18_linux-x64_bin.rpm
    mode: '0777'
    validate_certs: no
    
- name: rpm
  ansible.builtin.command:
    cmd: rpm -ivh jdk-18_linux-x64_bin.rpm
    chdir: /usr/java

